apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: clusterrolebinding
    app.kubernetes.io/instance: spacecraft-operator
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: spacecraft
    app.kubernetes.io/part-of: spacecraft
    app.kubernetes.io/managed-by: kustomize
  name: spacecraft-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: spacecraft-operator
subjects:
- kind: ServiceAccount
  name: spacecraft-operator
  namespace: default
