apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: serviceaccount
    app.kubernetes.io/instance: controller-manager-sa
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: spacecraft
    app.kubernetes.io/part-of: spacecraft
    app.kubernetes.io/managed-by: kustomize
  name: spacecraft-operator
  namespace: default
